name: Detect New Files
on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/*.md'  # Markdown ファイルの変更は無視
      - '**/*.yml' # Workflow ファイルの変更は無視

jobs:
  detect-new-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Detect new files
        run: |
          git diff --name-status HEAD^ HEAD | grep "^A" || exit 0
          echo "New files detected!"

